version: '3.3'

services:

  # Database Service (Mysql)
  mysql_database:
    image: mysql:8
    ports:
      - "3309:3306"
    restart: always #Always restart when error or stop
    environment:
      MYSQL_DATABASE: demo-springboot-docker-jenkins
      MYSQL_USER: demo-myapp
      MYSQL_PASSWORD: Demo123456789
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my-network

  # App config
  demo-springboot-docker-jenkins-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5593:8080"
    restart: always
    depends_on:
      - mysql_database # This service depends on mysql. Start that first.
    links:
      - mysql_database
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_database:3306/demo-springboot-docker-jenkins?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: demo-myapp
      SPRING_DATASOURCE_PASSWORD: Demo123456789
    networks:
      - my-network

# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  my-network: