version: '3.3'

services:

  # Database Service (Mysql)
  mysql_database:
    image: mysql:8
    ports:
      - "3309:3306"
    restart: always
    environment:
      MYSQL_DATABASE: demo-springboot-docker-jenkins
      MYSQL_USER: demo-myapp
      MYSQL_PASSWORD: Demo123456789
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-P", "3306", "-u", "root", "--password=root", "-e", "select 1", "DOCKERDB"]
      interval: 1s
      timeout: 3s
      retries: 30

  # App config
  my-app-demo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5593:8080"
    expose:
      - "5593"
    restart: always
    depends_on:
      - mysql_database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_database:3306/demo-springboot-docker-jenkins?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: demo-myapp
      SPRING_DATASOURCE_PASSWORD: Demo123456789
    networks:
      - my-network
    extra_hosts:
      - localhost:127.0.0.1

# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  my-network: